title: Vishnu Ponduri
logo: ![](/images/Vishnu Ponduri (1).jpg =250x250)
description: MS in Business Analytics and Information Managment, Purdue Univerisity
M.Tech, Construction Technology and Managment, NIT Trichy
logo: ![](images/purdue.png =250x250) ![](images/National_Institute_of_Technology_Trichy_Logo.png =250x250)
#show_downloads: true
theme: jekyll-theme-minimal
