title  : Vishnu Ponduri
#description : Master of science, Business Analytics and Information Managment, Purdue University
M.Tech, Construction Technology and managment, NIT Trichy
show_downloads : true
theme : jekyll-theme-minimal
